import type { OnboardingStep } from '@/lib/types/onboarding'

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: 1,
    route: '/roster',
    title: 'Build Your Roster',
    description: 'Add people you\'re interested in. Rate each on three dimensions: Looks (face), Personality (heart), and Reliability (star). These scores create your rankings.',
    spotlightTarget: '.roster-section',
    spotlightShape: 'rect',
    spotlightPadding: 16,
    allowInteraction: false,
    requiresAction: false,
    autoScroll: true,
  },
  {
    id: 2,
    route: '/roster',
    title: 'Add Your First Person',
    description: 'Tap here to add someone. You\'ll rate them on 3 scores to start building your rankings.',
    spotlightTarget: '.onboarding-add-button',
    spotlightShape: 'circle',
    spotlightPadding: 8,
    allowInteraction: true,
    requiresAction: false,
    autoScroll: true,
  },
  {
    id: 3,
    route: '/tonight',
    title: 'Get Tonight\'s Picks',
    description: 'Our algorithm ranks who you should reach out to based on ELO rating, reliability score, and how recently you connected. No more overthinking who to text!',
    spotlightTarget: '.tonight-recommendations',
    spotlightShape: 'rect',
    spotlightPadding: 16,
    allowInteraction: false,
    requiresAction: false,
    autoScroll: true,
    tabState: { activeTab: 'tonight' },
  },
  {
    id: 4,
    route: '/tonight',
    title: 'Battle to Rank',
    description: 'Can\'t decide who\'s really #1? Play head-to-head battles. Your picks update ELO ratings (like chess). The more you play, the smarter your rankings get.',
    spotlightTarget: '.battle-section',
    spotlightShape: 'rect',
    spotlightPadding: 16,
    allowInteraction: true,
    requiresAction: false,
    autoScroll: true,
    tabState: { activeTab: 'battle' },
  },
  {
    id: 5,
    route: '/profile',
    title: 'Track Your Progress',
    description: 'See your stats, unlock achievements, and customize your profile. 🎯 Pro tip: Sign in to sync your data across all devices and access full history.',
    spotlightTarget: '.profile-stats',
    spotlightShape: 'rect',
    spotlightPadding: 16,
    allowInteraction: false,
    requiresAction: false,
    autoScroll: true,
  },
  {
    id: 6,
    route: '/schedule',
    title: 'Share Your Availability',
    description: 'Set when you\'re free this week (6pm-2am) and generate a shareable link. They can view your schedule and share theirs back—coordinate without endless texts.',
    spotlightTarget: '.schedule-grid',
    spotlightShape: 'rect',
    spotlightPadding: 16,
    allowInteraction: true,
    requiresAction: false,
    autoScroll: true,
  },
  {
    id: 7,
    route: '/profile',
    title: 'Need Help Anytime?',
    description: 'Tap the yellow info button (bottom-right) anytime to revisit these tips or browse detailed FAQs. You\'ve got this! 🎉',
    spotlightTarget: null,
    spotlightShape: 'none',
    spotlightPadding: 0,
    allowInteraction: true,
    requiresAction: false,
    autoScroll: false,
  },
]
